global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks;
global using BuildingBlocks.CQRS;
global using Catalog.API.Models;
global using Marten;
global using Catalog.API.Exceptions;
global using Catalog.API.Products.Dtos;